name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install Docker Compose Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Build
        run: docker compose build app

      - name: Test
        run: docker compose run --rm app python manage.py test
